import { ImageSourcePropType } from 'react-native';

export interface Theme {
  id: string;
  name: string;
  preview: string;
  // Colors
  background: string;
  surface: string;
  text: string;
  textMuted: string;
  accent: string;
  border: string;
  navBackground: string;
  // Typography
  quoteFontFamily: string;
  uiFontFamily: string;
  // Background image (null = solid color)
  backgroundImage: ImageSourcePropType | null;
  // Dark/light mode
  isDark: boolean;
}

export const THEMES: Theme[] = [
  {
    id: 'minimal',
    name: 'Minimal',
    preview: 'Clean Black & White',
    background: '#0a0a0a',
    surface: '#1a1a1a',
    text: '#ffffff',
    textMuted: '#9ca3af',
    accent: '#ffffff',
    border: '#2a2a2a',
    navBackground: '#111111',
    quoteFontFamily: 'PlayfairDisplay_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: null,
    isDark: true,
  },
  {
    id: 'paper',
    name: 'Paper',
    preview: 'Warm Cream',
    background: '#f5f0e8',
    surface: '#ede8dc',
    text: '#2c2417',
    textMuted: '#7c6c54',
    accent: '#8b4513',
    border: '#d4c9b4',
    navBackground: '#ede8dc',
    quoteFontFamily: 'PlayfairDisplay_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: null,
    isDark: false,
  },
  {
    id: 'midnight',
    name: 'Midnight',
    preview: 'Deep Blue Night',
    background: '#0d1117',
    surface: '#161b22',
    text: '#e6edf3',
    textMuted: '#8b949e',
    accent: '#58a6ff',
    border: '#30363d',
    navBackground: '#161b22',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/midnight-bg.jpg'),
    isDark: true,
  },
  {
    id: 'forest',
    name: 'Forest',
    preview: 'Dark Green',
    background: '#0a1a0f',
    surface: '#102018',
    text: '#c8e6c9',
    textMuted: '#81a888',
    accent: '#4caf50',
    border: '#1b3a20',
    navBackground: '#102018',
    quoteFontFamily: 'PlayfairDisplay_700Bold',
    uiFontFamily: 'Inter_500Medium',
    backgroundImage: require('../assets/themes/forest-bg.jpg'),
    isDark: true,
  },
  {
    id: 'sunset',
    name: 'Sunset',
    preview: 'Warm Orange Glow',
    background: '#1a0a00',
    surface: '#2d1500',
    text: '#ffe0b2',
    textMuted: '#ffb74d',
    accent: '#ff6d00',
    border: '#4a2000',
    navBackground: '#2d1500',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/sunset-bg.jpg'),
    isDark: true,
  },
  {
    id: 'ocean',
    name: 'Ocean',
    preview: 'Deep Sea',
    background: '#001e3c',
    surface: '#002a52',
    text: '#e3f2fd',
    textMuted: '#90caf9',
    accent: '#29b6f6',
    border: '#003870',
    navBackground: '#002040',
    quoteFontFamily: 'PlayfairDisplay_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/ocean-bg.jpg'),
    isDark: true,
  },
  {
    id: 'rainy',
    name: 'Rainy Day',
    preview: 'Cozy Rain',
    background: '#1a1f2e',
    surface: '#252b3b',
    text: '#d4dde8',
    textMuted: '#8896a7',
    accent: '#7db3d4',
    border: '#303848',
    navBackground: '#252b3b',
    quoteFontFamily: 'PlayfairDisplay_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/rainy-bg.jpg'),
    isDark: true,
  },
  {
    id: 'foggy-window',
    name: 'Foggy Window',
    preview: 'Misty View',
    background: '#2a2a2a',
    surface: '#333333',
    text: '#e8e8e8',
    textMuted: '#aaaaaa',
    accent: '#cccccc',
    border: '#404040',
    navBackground: '#303030',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/foggy-bg.jpg'),
    isDark: true,
  },
  {
    id: 'cozy-cabin',
    name: 'Cozy Cabin',
    preview: 'Warm Firelight',
    background: '#1a0e00',
    surface: '#2d1a00',
    text: '#ffd89b',
    textMuted: '#c4935a',
    accent: '#e65c00',
    border: '#3d2200',
    navBackground: '#251200',
    quoteFontFamily: 'PlayfairDisplay_700Bold',
    uiFontFamily: 'Inter_500Medium',
    backgroundImage: require('../assets/themes/cabin-bg.jpg'),
    isDark: true,
  },
  {
    id: 'deep-waves',
    name: 'Deep Waves',
    preview: 'Underwater',
    background: '#00141e',
    surface: '#001e2e',
    text: '#b3e5fc',
    textMuted: '#4fc3f7',
    accent: '#0288d1',
    border: '#002a3e',
    navBackground: '#001828',
    quoteFontFamily: 'PlayfairDisplay_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/deep-waves-bg.jpg'),
    isDark: true,
  },
  {
    id: 'aurora',
    name: 'Aurora',
    preview: 'Northern Lights',
    background: '#050d1a',
    surface: '#0a1628',
    text: '#e0f7fa',
    textMuted: '#80cbc4',
    accent: '#26a69a',
    border: '#102030',
    navBackground: '#080f20',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/aurora-bg.jpg'),
    isDark: true,
  },
  {
    id: 'desert',
    name: 'Desert',
    preview: 'Warm Sand',
    background: '#1a120a',
    surface: '#2a1e10',
    text: '#f5deb3',
    textMuted: '#c4a882',
    accent: '#daa520',
    border: '#3a2e18',
    navBackground: '#241a0e',
    quoteFontFamily: 'PlayfairDisplay_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/desert-bg.jpg'),
    isDark: true,
  },
  {
    id: 'lavender',
    name: 'Lavender',
    preview: 'Soft Purple',
    background: '#1a1028',
    surface: '#251838',
    text: '#e8d5f5',
    textMuted: '#b39ddb',
    accent: '#9c27b0',
    border: '#332048',
    navBackground: '#1e1430',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/lavender-bg.jpg'),
    isDark: true,
  },
  {
    id: 'coffee',
    name: 'Coffee',
    preview: 'Rich Brown',
    background: '#1a0f08',
    surface: '#2a1a10',
    text: '#f5e6d3',
    textMuted: '#c4a882',
    accent: '#8b4513',
    border: '#3a2418',
    navBackground: '#241510',
    quoteFontFamily: 'PlayfairDisplay_700Bold',
    uiFontFamily: 'Inter_500Medium',
    backgroundImage: require('../assets/themes/coffee-bg.jpg'),
    isDark: true,
  },
  {
    id: 'sakura',
    name: 'Sakura',
    preview: 'Cherry Blossom',
    background: '#1a0d12',
    surface: '#2a1520',
    text: '#fce4ec',
    textMuted: '#f48fb1',
    accent: '#e91e63',
    border: '#3a2030',
    navBackground: '#22101a',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/sakura-bg.jpg'),
    isDark: true,
  },
];

export const DEFAULT_THEME_ID = 'minimal';

export function getTheme(id: string): Theme {
  return THEMES.find(t => t.id === id) ?? THEMES[0];
}
