import { ImageSourcePropType } from 'react-native';

export interface Theme {
  id: string;
  name: string;
  preview: string;
  // Colors
  background: string;
  surface: string;
  surfaceElevated: string;
  text: string;
  textMuted: string;
  accent: string;
  gold: string;
  goldButton: string;
  border: string;
  navBackground: string;
  // Typography
  quoteFontFamily: string;
  uiFontFamily: string;
  // Background image (null = solid color)
  backgroundImage: ImageSourcePropType | null;
  // Dark/light mode
  isDark: boolean;
}

export const THEMES: Theme[] = [
  // ── Default ───────────────────────────────────────────────────────────────
  {
    id: 'minimal',
    name: 'Minimal',
    preview: 'Warm Dark Gold',
    background: '#0D0D0D',
    surface: '#1C1A18',
    surfaceElevated: '#252220',
    text: '#E8E0D0',
    textMuted: '#6B6560',
    accent: '#B8975A',
    gold: '#B8975A',
    goldButton: '#C4A35A',
    border: '#2A2520',
    navBackground: '#1C1A18',
    quoteFontFamily: 'PlayfairDisplay_700Bold',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: null,
    isDark: true,
  },
  // ── Pink / pretty skies ───────────────────────────────────────────────────
  {
    id: 'rose-sky',
    name: 'Rose Sky',
    preview: 'Deep Rose Dark',
    background: '#140810',
    surface: '#1e1020',
    surfaceElevated: '#2a1530',
    text: '#fce4ec',
    textMuted: '#d080a8',
    accent: '#f06292',
    gold: '#e8a0c0',
    goldButton: '#f0b0d0',
    border: '#38163a',
    navBackground: '#190d1e',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/sakura-bg.jpg'),
    isDark: true,
  },
  {
    id: 'dusk',
    name: 'Dusk',
    preview: 'Twilight Purple-Pink',
    background: '#0e0818',
    surface: '#180e28',
    surfaceElevated: '#221438',
    text: '#f0d8ff',
    textMuted: '#a870d0',
    accent: '#c050f0',
    gold: '#c090e0',
    goldButton: '#d0a0f0',
    border: '#2c1a42',
    navBackground: '#130b20',
    quoteFontFamily: 'PlayfairDisplay_400Regular_Italic',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/lavender-bg.jpg'),
    isDark: true,
  },
  // ── Beach ─────────────────────────────────────────────────────────────────
  {
    id: 'shore',
    name: 'Shore',
    preview: 'Rocky Coast at Dusk',
    background: '#0c1520',
    surface: '#141e2c',
    surfaceElevated: '#1c2a38',
    text: '#e8f4f8',
    textMuted: '#80a8c0',
    accent: '#40b8d8',
    gold: '#B8975A',
    goldButton: '#C4A35A',
    border: '#1a2a38',
    navBackground: '#0e1828',
    quoteFontFamily: 'PlayfairDisplay_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/shore-bg.jpg'),
    isDark: true,
  },
  // ── High energy ───────────────────────────────────────────────────────────
  {
    id: 'ember',
    name: 'Ember',
    preview: 'Fiery Orange',
    background: '#120400',
    surface: '#1e0800',
    surfaceElevated: '#2c1000',
    text: '#ffe8d0',
    textMuted: '#ff9060',
    accent: '#ff5500',
    gold: '#ff9040',
    goldButton: '#ffaa50',
    border: '#361200',
    navBackground: '#180600',
    quoteFontFamily: 'PlayfairDisplay_700Bold',
    uiFontFamily: 'Inter_600SemiBold',
    backgroundImage: require('../assets/themes/sunset-bg.jpg'),
    isDark: true,
  },
  // ── Storm / drama ─────────────────────────────────────────────────────────
  {
    id: 'tempest',
    name: 'Tempest',
    preview: 'Dramatic Lightning Blue',
    background: '#05080f',
    surface: '#0a0e1a',
    surfaceElevated: '#131822',
    text: '#d0d8f0',
    textMuted: '#3858a8',
    accent: '#3870d8',
    gold: '#5888e0',
    goldButton: '#6898f0',
    border: '#0e1628',
    navBackground: '#070b14',
    quoteFontFamily: 'EBGaramond_700Bold',
    uiFontFamily: 'Inter_600SemiBold',
    backgroundImage: require('../assets/themes/tempest-bg.jpg'),
    isDark: true,
  },
  // ── Forest / nature ───────────────────────────────────────────────────────
  {
    id: 'woodland',
    name: 'Woodland',
    preview: 'Earthy Moss Green',
    background: '#060d08',
    surface: '#0d1810',
    surfaceElevated: '#152012',
    text: '#cce8c0',
    textMuted: '#427838',
    accent: '#40a850',
    gold: '#68c058',
    goldButton: '#78d068',
    border: '#183018',
    navBackground: '#091210',
    quoteFontFamily: 'Lora_700Bold',
    uiFontFamily: 'Nunito_600SemiBold',
    backgroundImage: require('../assets/themes/woodland-bg.jpg'),
    isDark: true,
  },
  {
    id: 'botanical',
    name: 'Botanical',
    preview: 'Lush Spring Emerald',
    background: '#050c06',
    surface: '#0c1a0e',
    surfaceElevated: '#142216',
    text: '#d0f0d4',
    textMuted: '#389048',
    accent: '#28d050',
    gold: '#50e068',
    goldButton: '#60f078',
    border: '#163020',
    navBackground: '#081210',
    quoteFontFamily: 'Lora_700Bold',
    uiFontFamily: 'Nunito_400Regular',
    backgroundImage: require('../assets/themes/plant-bg.jpg'),
    isDark: true,
  },
  // ── Moon / night ──────────────────────────────────────────────────────────
  {
    id: 'lunar',
    name: 'Lunar',
    preview: 'Soft Moonbeam Silver',
    background: '#07081a',
    surface: '#0f1022',
    surfaceElevated: '#17182e',
    text: '#e4e2f8',
    textMuted: '#5858a0',
    accent: '#9090d8',
    gold: '#a8a8e8',
    goldButton: '#b8b8f0',
    border: '#1c1c38',
    navBackground: '#0b0c1e',
    quoteFontFamily: 'Cormorant_300Light',
    uiFontFamily: 'Raleway_300Light',
    backgroundImage: require('../assets/themes/lunar-bg.jpg'),
    isDark: true,
  },
  {
    id: 'crescent',
    name: 'Crescent',
    preview: 'Nocturnal Teal Glow',
    background: '#050c10',
    surface: '#0b1820',
    surfaceElevated: '#13222e',
    text: '#cce8f0',
    textMuted: '#307898',
    accent: '#40a8c8',
    gold: '#60c0d8',
    goldButton: '#70d0e8',
    border: '#0e2030',
    navBackground: '#071418',
    quoteFontFamily: 'Cormorant_700Bold',
    uiFontFamily: 'Raleway_300Light',
    backgroundImage: require('../assets/themes/crescent-bg.jpg'),
    isDark: true,
  },
  // ── Sunrise / warmth ──────────────────────────────────────────────────────
  {
    id: 'daybreak',
    name: 'Daybreak',
    preview: 'Warm Sunrise Coral',
    background: '#160804',
    surface: '#200e06',
    surfaceElevated: '#2e1810',
    text: '#fde4cc',
    textMuted: '#c87848',
    accent: '#e87838',
    gold: '#e89050',
    goldButton: '#f0a060',
    border: '#38180c',
    navBackground: '#1a0c06',
    quoteFontFamily: 'DMSerifDisplay_400Regular_Italic',
    uiFontFamily: 'Nunito_400Regular',
    backgroundImage: require('../assets/themes/daybreak-bg.jpg'),
    isDark: true,
  },
  // ── Mountain / ice ────────────────────────────────────────────────────────
  {
    id: 'alpine',
    name: 'Alpine',
    preview: 'Crisp Glacier Ice',
    background: '#07101a',
    surface: '#0f1a24',
    surfaceElevated: '#172430',
    text: '#d8e8f4',
    textMuted: '#5080b0',
    accent: '#5898d8',
    gold: '#78b0e0',
    goldButton: '#88c0f0',
    border: '#162230',
    navBackground: '#0a1420',
    quoteFontFamily: 'DMSerifDisplay_400Regular',
    uiFontFamily: 'Raleway_600SemiBold',
    backgroundImage: require('../assets/themes/alpine-bg.jpg'),
    isDark: true,
  },
  // ── Soft / romantic ───────────────────────────────────────────────────────
  {
    id: 'blush',
    name: 'Blush',
    preview: 'Cotton Candy Rose',
    background: '#180c16',
    surface: '#221020',
    surfaceElevated: '#2e162c',
    text: '#fcdcea',
    textMuted: '#c068a0',
    accent: '#e878b8',
    gold: '#f098c8',
    goldButton: '#f8a8d8',
    border: '#3a1830',
    navBackground: '#1c1018',
    quoteFontFamily: 'Cormorant_400Regular_Italic',
    uiFontFamily: 'Raleway_400Regular',
    backgroundImage: require('../assets/themes/cotton-candy-bg.jpg'),
    isDark: true,
  },
  // ── Stark / textural ──────────────────────────────────────────────────────
  {
    id: 'obsidian',
    name: 'Obsidian',
    preview: 'Stark Charcoal Silver',
    background: '#090808',
    surface: '#131110',
    surfaceElevated: '#1d1918',
    text: '#e8e4e0',
    textMuted: '#686460',
    accent: '#a8a09a',
    gold: '#c0b8b2',
    goldButton: '#d0c8c2',
    border: '#272320',
    navBackground: '#0d0b0a',
    quoteFontFamily: 'Cormorant_600SemiBold',
    uiFontFamily: 'Inter_500Medium',
    backgroundImage: require('../assets/themes/obsidian-bg.jpg'),
    isDark: true,
  },
  {
    id: 'apex',
    name: 'Apex',
    preview: 'Raw Power Monochrome',
    background: '#060606',
    surface: '#101010',
    surfaceElevated: '#1c1c1c',
    text: '#f0f0f0',
    textMuted: '#787878',
    accent: '#c0c0c0',
    gold: '#d8d8d8',
    goldButton: '#e8e8e8',
    border: '#282828',
    navBackground: '#0c0c0c',
    quoteFontFamily: 'Allkin_400Regular',
    uiFontFamily: 'Inter_700Bold',
    backgroundImage: require('../assets/themes/lion-bg.jpg'),
    isDark: true,
  },
  // ── Shore / sand ──────────────────────────────────────────────────────────
  {
    id: 'seashore',
    name: 'Seashore',
    preview: 'Golden Harvest Sand',
    background: '#0e0804',
    surface: '#1a1008',
    surfaceElevated: '#26180e',
    text: '#fce8c8',
    textMuted: '#b89060',
    accent: '#d8a048',
    gold: '#c89038',
    goldButton: '#d8a848',
    border: '#2e1c0c',
    navBackground: '#140e06',
    quoteFontFamily: 'EBGaramond_400Regular',
    uiFontFamily: 'Inter_400Regular',
    backgroundImage: require('../assets/themes/golden-shore-bg.jpg'),
    isDark: true,
  },
  // ── Space ─────────────────────────────────────────────────────────────────
  {
    id: 'galaxy',
    name: 'Galaxy',
    preview: 'Deep Nebula Violet',
    background: '#030408',
    surface: '#08091a',
    surfaceElevated: '#0e1024',
    text: '#d8d0f8',
    textMuted: '#4840a8',
    accent: '#6858c8',
    gold: '#8878d8',
    goldButton: '#9888e8',
    border: '#101224',
    navBackground: '#060814',
    quoteFontFamily: 'Lora_400Regular_Italic',
    uiFontFamily: 'Raleway_600SemiBold',
    backgroundImage: require('../assets/themes/galaxy-bg.jpg'),
    isDark: true,
  },
  {
    id: 'orbit',
    name: 'Orbit',
    preview: 'Vast Ionosphere Blue',
    background: '#010306',
    surface: '#04080e',
    surfaceElevated: '#0b1220',
    text: '#b8d4f8',
    textMuted: '#1858c0',
    accent: '#0878e8',
    gold: '#3098f8',
    goldButton: '#40a8ff',
    border: '#061828',
    navBackground: '#030710',
    quoteFontFamily: 'EBGaramond_700Bold',
    uiFontFamily: 'Inter_500Medium',
    backgroundImage: require('../assets/themes/orbit-bg.jpg'),
    isDark: true,
  },
];

export const DEFAULT_THEME_ID = 'minimal';

export function getTheme(id: string): Theme {
  return THEMES.find(t => t.id === id) ?? THEMES[0];
}
