package __PACKAGE__.widgetpin

import android.appwidget.AppWidgetManager
import android.content.ComponentName
import android.os.Build
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.bridge.ReactContextBaseJavaModule
import com.facebook.react.bridge.ReactMethod

/**
 * Raises the launcher's own "add widget to Home Screen" dialog.
 *
 * There is no success callback. Whether the user actually went through with it
 * is read back by enumerating placed widgets when the app next returns to the
 * foreground (WidgetBridge.getActiveWidgets), which is the same path a widget
 * added straight from the launcher takes — one mechanism covers both.
 *
 * Copied into the generated project and registered by
 * plugins/withWidgetPinModule.js, which substitutes __PACKAGE__.
 */
class WidgetPinModule(reactContext: ReactApplicationContext) :
  ReactContextBaseJavaModule(reactContext) {

  override fun getName() = NAME

  @ReactMethod
  fun requestPin(promise: Promise) {
    // requestPinAppWidget landed in Android 8.0. Below that, and on launchers
    // that decline, the JS side falls back to manual instructions.
    if (Build.VERSION.SDK_INT < Build.VERSION_CODES.O) {
      promise.reject(ERR_UNSUPPORTED, "Widget pinning requires Android 8.0 or newer")
      return
    }

    try {
      val context = reactApplicationContext
      val manager = AppWidgetManager.getInstance(context)

      if (!manager.isRequestPinAppWidgetSupported) {
        promise.reject(ERR_UNSUPPORTED, "This launcher does not support widget pinning")
        return
      }

      // Generated by react-native-android-widget's config plugin from the
      // BasicWidget entry in app.json: it writes the provider class into
      // <package>.widget, so the name is derived rather than hardcoded.
      val provider = ComponentName(context.packageName, "${context.packageName}.widget.$PROVIDER_NAME")

      if (manager.requestPinAppWidget(provider, null, null)) {
        promise.resolve(true)
      } else {
        promise.reject(ERR_REJECTED, "The launcher rejected the pin request")
      }
    } catch (e: Exception) {
      promise.reject(ERR_REJECTED, e.message, e)
    }
  }

  companion object {
    const val NAME = "WidgetPin"
    private const val PROVIDER_NAME = "BasicWidget"
    private const val ERR_UNSUPPORTED = "E_PIN_UNSUPPORTED"
    private const val ERR_REJECTED = "E_PIN_REJECTED"
  }
}
