/**
 * Expo config plugin — fixes react-native-android-widget generating
 * `android:exported="false"` for the BasicWidget receiver.
 *
 * Android 12+ requires AppWidget providers to be exported so that
 * the system can register them with AppWidgetManager. Without this,
 * `AppWidgetManager.getInstalledProviders()` never returns the provider,
 * making `getWidgetInfo('BasicWidget')` always return [] and the widget
 * list screen always show "No widgets yet".
 */
const { withAndroidManifest } = require('@expo/config-plugins');

module.exports = function withWidgetExported(config) {
  return withAndroidManifest(config, (mod) => {
    const manifest = mod.modResults;
    const receivers = manifest.manifest?.application?.[0]?.receiver ?? [];

    for (const receiver of receivers) {
      const name = receiver.$?.['android:name'] ?? '';
      // Target the BasicWidget receiver generated by react-native-android-widget
      if (name.endsWith('BasicWidget')) {
        receiver.$['android:exported'] = 'true';
      }
    }

    return mod;
  });
};
