import Purchases, { LOG_LEVEL } from 'react-native-purchases';
import { Platform } from 'react-native';

// iOS key: RevenueCat dashboard → (your iOS app) → API Keys → Public SDK Key (starts with appl_)
const REVENUECAT_API_KEY = Platform.select({
  ios: 'appl_ZdEOrrPGxYzZwjTMVuoiWzQZNQm',
  android: 'goog_fqnpPxNEvjAxDwwUmmLJkOnIofu',
})!;

/** Entitlement identifier for "Quotable Premium" subscription */
export const ENTITLEMENT_PRO = 'Quotable Premium';

/** Initialize RevenueCat SDK */
export async function initializeRevenueCat(): Promise<void> {
  try {
    // Must be set before configure() to capture the store handshake, which is
    // where a missing product or unsigned agreement actually reports itself.
    if (__DEV__) Purchases.setLogLevel(LOG_LEVEL.VERBOSE);

    // Configure SDK with API key
    Purchases.configure({ apiKey: REVENUECAT_API_KEY });

    if (__DEV__) console.log('✅ RevenueCat initialized successfully');
  } catch (error) {
    if (__DEV__) console.error('❌ RevenueCat initialization failed:', error);
    throw error;
  }
}

/** Get the current user ID (may be generated by RevenueCat) */
export async function getUserID(): Promise<string> {
  try {
    return await Purchases.getAppUserID();
  } catch (error) {
    if (__DEV__) console.error('Error getting user ID:', error);
    throw error;
  }
}

/** Check if user has "Quotable Premium" entitlement */
export async function hasProEntitlement(): Promise<boolean> {
  try {
    const customerInfo = await Purchases.getCustomerInfo();
    return customerInfo.entitlements.active[ENTITLEMENT_PRO] !== undefined;
  } catch (error) {
    if (__DEV__) console.error('Error checking entitlement:', error);
    return false;
  }
}

/** Get full customer info (purchases, entitlements, etc.) */
export async function getCustomerInfo() {
  try {
    return await Purchases.getCustomerInfo();
  } catch (error) {
    if (__DEV__) console.error('Error fetching customer info:', error);
    throw error;
  }
}

/** Get available offerings & products */
export async function getOfferings() {
  try {
    const offerings = await Purchases.getOfferings();
    return offerings;
  } catch (error) {
    if (__DEV__) console.error('Error fetching offerings:', error);
    throw error;
  }
}

/** Purchase a package */
export async function purchasePackage(packageId: string, offering: string) {
  try {
    const offerings = await Purchases.getOfferings();
    // PurchasesOffering exposes availablePackages — there is no packagesById map.
    const selectedPackage = offerings.all[offering]?.availablePackages.find(
      (p) => p.identifier === packageId,
    );

    if (!selectedPackage) {
      throw new Error(`Package ${packageId} not found in offering ${offering}`);
    }

    const result = await Purchases.purchasePackage(selectedPackage);
    return result;
  } catch (error) {
    if (__DEV__) console.error('Purchase failed:', error);
    throw error;
  }
}

/** Restore purchases from App Store / Play Store */
export async function restorePurchases() {
  try {
    const result = await Purchases.restorePurchases();
    if (__DEV__) console.log('✅ Purchases restored');
    return result;
  } catch (error) {
    if (__DEV__) console.error('Restore purchases failed:', error);
    throw error;
  }
}

/** Set custom user ID (e.g., after login) */
export async function setAppUserID(userID: string) {
  try {
    await Purchases.logIn(userID);
    if (__DEV__) console.log('✅ User ID set');
  } catch (error) {
    if (__DEV__) console.error('Error setting user ID:', error);
    throw error;
  }
}

/** Log out the current user */
export async function logout() {
  try {
    await Purchases.logOut();
    if (__DEV__) console.log('✅ User logged out');
  } catch (error) {
    if (__DEV__) console.error('Error logging out:', error);
    throw error;
  }
}
