import Purchases from 'react-native-purchases';

/** RevenueCat API Key (test key provided) */
const REVENUECAT_API_KEY = 'test_vMJWzIBFIQvlbwxFbmgSFfPUrKu';

/** Entitlement identifier for "Quotes Pro" subscription */
export const ENTITLEMENT_PRO = 'Quotes Pro';

/** Initialize RevenueCat SDK */
export async function initializeRevenueCat(): Promise<void> {
  try {
    // Configure SDK with API key
    await Purchases.configure({
      apiKey: REVENUECAT_API_KEY,
      appUserID: undefined, // Will auto-generate anonymous ID
    });

    console.log('✅ RevenueCat initialized successfully');
  } catch (error) {
    console.error('❌ RevenueCat initialization failed:', error);
    throw error;
  }
}

/** Get the current user ID (may be generated by RevenueCat) */
export async function getUserID(): Promise<string> {
  try {
    return await Purchases.getAppUserID();
  } catch (error) {
    console.error('Error getting user ID:', error);
    throw error;
  }
}

/** Check if user has "Quotes Pro" entitlement */
export async function hasProEntitlement(): Promise<boolean> {
  try {
    const customerInfo = await Purchases.getCustomerInfo();
    return customerInfo.entitlements.active[ENTITLEMENT_PRO] !== undefined;
  } catch (error) {
    console.error('Error checking entitlement:', error);
    return false;
  }
}

/** Get full customer info (purchases, entitlements, etc.) */
export async function getCustomerInfo() {
  try {
    return await Purchases.getCustomerInfo();
  } catch (error) {
    console.error('Error fetching customer info:', error);
    throw error;
  }
}

/** Get available offerings & products */
export async function getOfferings() {
  try {
    const offerings = await Purchases.getOfferings();
    return offerings;
  } catch (error) {
    console.error('Error fetching offerings:', error);
    throw error;
  }
}

/** Purchase a package */
export async function purchasePackage(packageId: string, offering: string) {
  try {
    const offerings = await Purchases.getOfferings();
    const selectedPackage = offerings.all[offering]?.packagesById[packageId];

    if (!selectedPackage) {
      throw new Error(`Package ${packageId} not found in offering ${offering}`);
    }

    const result = await Purchases.purchasePackage(selectedPackage);
    return result;
  } catch (error) {
    console.error('Purchase failed:', error);
    throw error;
  }
}

/** Restore purchases from App Store / Play Store */
export async function restorePurchases() {
  try {
    const result = await Purchases.restorePurchases();
    console.log('✅ Purchases restored:', result);
    return result;
  } catch (error) {
    console.error('Restore purchases failed:', error);
    throw error;
  }
}

/** Set custom user ID (e.g., after login) */
export async function setAppUserID(userID: string) {
  try {
    await Purchases.logIn(userID);
    console.log('✅ User ID set:', userID);
  } catch (error) {
    console.error('Error setting user ID:', error);
    throw error;
  }
}

/** Log out the current user */
export async function logout() {
  try {
    await Purchases.logOut();
    console.log('✅ User logged out');
  } catch (error) {
    console.error('Error logging out:', error);
    throw error;
  }
}
